[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ignored_warnings_from = ["src"]

# [profile.default.lint]
# deny_warnings = false

remappings = [
    '@chainlink/contracts=lib/chainlink-brownie-contracts/contracts',
    '@solmate=lib/solmate/src/',
]

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
